### ISSUE TITLE
 12k tone from pastelverb on headphones.

### ISSUE THREAD

**Issue by plodplodplod** [landonviator/viatordsp#11]
I was playing around with the settings and got a 12655hz tone when I turned resonance up, happens even without any input or upstream effects.

**Comment by landonviator** [comment]
Hey @plodplodplod, thanks for this, just fixed it. Problem was the resonance dial went up to 100, it should go less, so I just set it to 90.

**Comment by plodplodplod** [comment]
Great, thanks!
